package chapters.chapter_12.Checkpoints;

public class Checkpoint_01_02_03_04 {

    /*1
    *
    * throwing an exception to its caller method for it can be capable of handling this exception. without exception handling program would be terminated.
    *
    * 2
    *
    * 1/0 will throw an Aritmethic exception
    *
    * 3
    *
    * MAx_VALUE + 1 will be a problem because it pass the max value permitted for long type
    *
    * 4
    *
    *it first looks for a exception handler in try-catch. we use try-catch in our program to catch an exception
    *
    * */
}
